name: "Azure OpenAPI"

resources:
  repositories:
  - repository: ref
    type: github
    name: openapi-env-test/openapi-platform-pipelines
    ref: refs/heads/master
    endpoint: openapi-env-test

variables:
- template: .azure-pipelines/main-SwaggerSpecs-ProdVar.yml@ref

jobs:
- template: .azure-pipelines/main-SwaggerSpecs-ProdJobs.yml@ref