name: "Preproduction CI for Azure Rest API specifications"

resources:
  repositories:
    - repository: ref
      type: github
      name: test-repo-tih/openapi-platform-pipelines
      ref: refs/heads/pre-production-swagger-specs

variables:
  - template: .azure-pipelines/main-SwaggerSpecs-PreProdVar.yaml@ref

jobs:
  - template: .azure-pipelines/main-SwaggerSpecs-PreProdJobs.yaml@ref
