parameters:
- name: jobName
  type: string
  default: ''
- name: repoName
  type: string
  default: ''

jobs:
- job: ${{ parameters.jobName }}
  displayName: ${{ parameters.jobName }}
  pool:
    vmImage: 'Ubuntu 18.04'
  timeoutInMinutes: 180
  dependsOn: FilterSdkRepos
  condition: contains(dependencies.FilterSdkRepos.outputs['FilterSdkRepos.EnabledJobs'], '|${{ parameters.repoName }}|')
  variables:
  - template: common/Variables.yml
    parameters:
      sdkRepoName: ${{ parameters.repoName }}
  steps:
  - checkout: none
  - template: common/GetPRNumber.yml
  - template: common/PullImage.yml
  - template: common/RunSDKAutomation.yml
